let detailId = $('#detailId'),
    capId = $('#capId'),
    breadCrumb = $('.detail_breadcrumb'),
    brewName = $('.detail_brewName'),
    itemName = $('.detail_item_name'),
    itemPics = $('.detail_carousel'),
    itemDescript = $('.detail_item_content'),
    itemDescript2 = $('.item_feture_description'),
    itemPrice = $('.detail_item_price'),
    itemRegion = $('.detail_item_region'),
    itemPref = $('.detail_item_pref'),
    itemVCatag = $('.detail_item_var'),
    itemRice = $('.detail_item_rice'),
    itemShudo = $('.detail_item_shudo'),
    itemCap = $('.detail_item_cap'),
    itemAcid = $('.detail_item_acidity'),
    itemAmino = $('.detail_item_amino'),
    itemSeimai = $('.detail_item_seimaibuai'),
    itemSelCap = $('#item_select_cap'),
    recItem = $('.recommand_carousel'),

    addCart = $('.item_addCart'),

    minusQty = $('.detail_item_minus'),
    plusQty = $('.detail_item_plus'),
    currectQty = $('.detail_item_hold')